# Autogenerated wrapper script for TinyGismo_jll for aarch64-apple-darwin-julia_version+1.13.0
export libjltinygismo

using libcxxwrap_julia_jll
using gismo_jll
JLLWrappers.@generate_wrapper_header("TinyGismo")
JLLWrappers.@declare_library_product(libjltinygismo, "@rpath/libjltinygismo.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, gismo_jll)
    JLLWrappers.@init_library_product(
        libjltinygismo,
        "lib/libjltinygismo.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
